// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVT12QcqsVSOmfNOUd4NWPC_siSlsuA44',
    appId: '1:228733719016:web:684ac84b6c9929fdae145d',
    messagingSenderId: '228733719016',
    projectId: 'favourite-chuck-jokes',
    authDomain: 'favourite-chuck-jokes.firebaseapp.com',
    storageBucket: 'favourite-chuck-jokes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC66Ic0Qv1v9ojr5rO4ZglNrRgUzoO7Dj8',
    appId: '1:228733719016:android:9f4035cfe999cde9ae145d',
    messagingSenderId: '228733719016',
    projectId: 'favourite-chuck-jokes',
    storageBucket: 'favourite-chuck-jokes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi3aeYzSCs3B8kAuJ0NiFr9jG2iVp6NIc',
    appId: '1:228733719016:ios:59d655ccc8a83ae7ae145d',
    messagingSenderId: '228733719016',
    projectId: 'favourite-chuck-jokes',
    storageBucket: 'favourite-chuck-jokes.appspot.com',
    iosClientId: '228733719016-i987coud6di9rkbac45lo5qgumsdcs02.apps.googleusercontent.com',
    iosBundleId: 'com.example.chucknorris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi3aeYzSCs3B8kAuJ0NiFr9jG2iVp6NIc',
    appId: '1:228733719016:ios:59d655ccc8a83ae7ae145d',
    messagingSenderId: '228733719016',
    projectId: 'favourite-chuck-jokes',
    storageBucket: 'favourite-chuck-jokes.appspot.com',
    iosClientId: '228733719016-i987coud6di9rkbac45lo5qgumsdcs02.apps.googleusercontent.com',
    iosBundleId: 'com.example.chucknorris',
  );
}
